
directory: build/plots/
source: false
# TODO: publication-quality is 600dpi
dpi: 150
format: PNG
caption_format: markdown+raw_tex

logging:
  verbosity: info
  # filepath: build/plot-log.txt

matplotlib:
  preamble: plotting.py
  tight_bbox: true
  transparent: true
  executable: python

